# This workflow is triggered every hour
# and runs:
# bash generate-csvs.sh
# to update the data files
# and then commits the changes to the repo

on:
  schedule:
    - cron: '11 * * * *'
  # and on puzh
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  keepalive-job:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate CSVs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bash data/generate-csvs.sh
